# Generated by Django 4.0.1 on 2022-01-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmodel',
            name='company_name',
            field=models.CharField(default='Coupcode Tech', max_length=100),
            preserve_default=False,
        ),
    ]
