# Generated by Django 4.0.1 on 2022-01-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_mailmodel_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmodel',
            name='company_email',
            field=models.EmailField(default='company@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
